services:
  spark-master:
    build: ./spark
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "7077:7077"   # Spark master
      - "8080:8080"   # Spark master UI
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    networks:
      - datalakehouse_net

  spark-worker:
    build: ./spark
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_PORT=8881
      - SPARK_WORKER_WEBUI_PORT=8081
    depends_on:
      - spark-master
    ports:
      - "8081:8081"   # Spark worker UI
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    networks:
      - datalakehouse_net
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 endpoint
      - "9001:9001"   # MinIO console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks:
      - datalakehouse_net

  # postgres:
  #   image: bitnami/postgresql:14.5.0-debian-11-r26
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: nessie
  #     POSTGRES_PASSWORD: nessie
  #     POSTGRES_DB: nessie
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/bitnami/postgresql
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U nessie -d nessie"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - datalakehouse_net

  nessie:
    image: ghcr.io/projectnessie/nessie:0.102.5
    container_name: nessie
    environment:
      - QUARKUS_HTTP_PORT=19120
      - QUARKUS_PROFILE=prod
      - NESSIE_VERSION_STORE_TYPE=JDBC2
      # - nessie.version.store.persist.jdbc.datasource=postgresql
      # - quarkus.datasource.postgresql.jdbc.url=jdbc:postgresql://postgres:5432/nessie
      # - quarkus.datasource.postgresql.username=root
      # - quarkus.datasource.postgresql.password=root
      # - nessie.server.authentication.enabled=false
      - NESSIE_VERSION_STORE_PERSIST_JDBC_DATASOURCE=postgresql
      - QUARKUS_DATASOURCE_postgresql_JDBC_URL=jdbc:postgresql://postgres:5432/nessie
      - QUARKUS_DATASOURCE_postgresql_USERNAME=root
      - QUARKUS_DATASOURCE_postgresql_PASSWORD=root
      - NESSIE_SERVER_AUTHENTICATION_ENABLED=false
    ports:
      - "19120:19120"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - datalakehouse_net

# THÊM JUPYTER SERVICE - sử dụng cùng image
  jupyter:
    build: ./spark  
    container_name: jupyter
    hostname: jupyter
    environment:
      - SPARK_MODE=jupyter  
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/iceberg/notebooks
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    depends_on:
      - spark-master
      - minio
    networks:
      - datalakehouse_net
    # entrypoint để chỉ chạy Jupyter  
    entrypoint: ["jupyter", "notebook"]
    command: [
      "--ip=0.0.0.0",
      "--port=8888", 
      "--no-browser",
      "--allow-root",
      "--ServerApp.token=''",
      "--ServerApp.password=''",
      "--ServerApp.allow_origin='*'",
      "--ServerApp.trust_xheaders=True"
    ]
  vector-database:
      image: qdrant/qdrant:v1.11.5
      container_name: qdrant
      ports:
        - "6333:6333"   # REST API
        - "6334:6334"   # gRPC API
      volumes:
        - qdrant_vector_storage:/qdrant/storage
      networks:
        - datalakehouse_net

  # ==========================
  # AIRFLOW (LOCAL EXECUTOR)
  # ==========================
  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nessie     # database mặc định sẽ được tạo lúc đầu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # dùng để tạo thêm DB khác
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d nessie"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - datalakehouse_net

  airflow:
    image: apache/airflow:2.7.1
    container_name: airflow
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://root:root@postgres:5432/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./comment_data/raw:/opt/airflow/data/raw
      - ./airflow/entrypoint.sh:/opt/airflow/entrypoint.sh
    entrypoint: ["/bin/bash", "/opt/airflow/entrypoint.sh"]
    ports:
      - "8088:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - datalakehouse_net


  # ==========================
networks:
  datalakehouse_net:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  qdrant_vector_storage:
  airflow_db_data: